name: ci

on: [push, pull_request]

jobs:
  ci:
    name: ci
    runs-on: macos-12
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install requirements
        run: brew install go-task meson ninja

      - name: Print tool versions
        run: task tool-versions

      - name: Determine version
        id: version
        run: |
          case "${GITHUB_REF}" in
          refs/tags/*)
            VERSION=${GITHUB_REF#refs/tags/}
            ;;
          *)
            VERSION=develop
            ;;
          esac

          echo "version=${VERSION}" >> $GITHUB_OUTPUT
          echo ${VERSION}

      - name: Build
        # macOS runners have unknown resource limits (timeout or number of open
        # files…) that prevent the execution of a single Taskfile task that
        # manages all builds. Concurrent tasks must be limited.
        run: |
          VERSION=${{ steps.version.outputs.version }}
          make build/output/libmpv-libs_${VERSION}_ios-arm64-audio.tar.gz
          make build/output/libmpv-libs_${VERSION}_ios-arm64-video.tar.gz
          make build/output/libmpv-libs_${VERSION}_iossimulator-universal-audio.tar.gz
          make build/output/libmpv-libs_${VERSION}_iossimulator-universal-video.tar.gz
          make build/output/libmpv-libs_${VERSION}_macos-universal-audio.tar.gz
          make build/output/libmpv-libs_${VERSION}_macos-universal-video.tar.gz
          make build/output/libmpv-xcframeworks_${VERSION}_ios-universal-audio.tar.gz
          make build/output/libmpv-xcframeworks_${VERSION}_ios-universal-video.tar.gz
          make build/output/libmpv-xcframeworks_${VERSION}_macos-universal-audio.tar.gz
          make build/output/libmpv-xcframeworks_${VERSION}_macos-universal-video.tar.gz

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          if-no-files-found: error
          path: |
            build/tool-versions.lock
            build/**/*.tar.gz

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          fail_on_unmatched_files: true
          files: |
            build/tool-versions.lock
            build/**/*.tar.gz
