name: ci

on: [push, pull_request]

jobs:
  ci:
    name: ci
    runs-on: macos-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install requirements
        run: brew install go-task meson ninja

      - name: Print tool versions
        run: task tool-versions

      - name: Determine version
        id: version
        run: echo "version=${GITHUB_REF#refs/*/}" >> $GITHUB_OUTPUT

      - name: Build
        run: |
          VERSION=${{ steps.version.outputs.version }} task

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          if-no-files-found: error
          path: |
            build/tool-versions.lock
            build/**/*.tar.gz

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          fail_on_unmatched_files: true
          files: |
            build/tool-versions.lock
            build/**/*.tar.gz
